### ISSUE TITLE
 import failed

### ISSUE THREAD

**Issue by ghost** [MGTEK/pyetw#1]
**Python v-3.11.1, Windows 11 latest**
**Code:**
import logging
import pyetw as etw

logging.basicConfig(level=logging.DEBUG, handlers=(etw.LoggerHandler(),))
logging.info("Hello from PyEtw!")

**Run:**
File "C:...\pyetw\pyetw.py", line 158, in EventProvider
    _EventRegister = _etw_function(
    TypeError: 'staticmethod' object is not callable

**Comment by mariusgreuel** [comment]
Thanks for the report! Seems like I snuck in a Python 3.10+ construct during the last refactoring. Just pushed a fix, you can install it via `pip install --upgrade pyetw`.
